// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJebpw2Z-xKEqoDbUjRcKFnj08vhYNV_w',
    appId: '1:697443357296:web:49ff81ed8737331ebb5ab5',
    messagingSenderId: '697443357296',
    projectId: 'hlrc-projeto',
    authDomain: 'hlrc-projeto.firebaseapp.com',
    storageBucket: 'hlrc-projeto.firebasestorage.app',
    measurementId: 'G-P5VRPF2KJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGN8Wl0zFQVF9SvQv0NK59gQl20rzNCM',
    appId: '1:697443357296:android:d5fec8d987e45f19bb5ab5',
    messagingSenderId: '697443357296',
    projectId: 'hlrc-projeto',
    storageBucket: 'hlrc-projeto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCHFRP3Y6krJMUOrBcrPiXh5w98MPqpI',
    appId: '1:697443357296:ios:be51bedfb9293c0ebb5ab5',
    messagingSenderId: '697443357296',
    projectId: 'hlrc-projeto',
    storageBucket: 'hlrc-projeto.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdCHFRP3Y6krJMUOrBcrPiXh5w98MPqpI',
    appId: '1:697443357296:ios:be51bedfb9293c0ebb5ab5',
    messagingSenderId: '697443357296',
    projectId: 'hlrc-projeto',
    storageBucket: 'hlrc-projeto.firebasestorage.app',
    iosBundleId: 'com.example.educacenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJebpw2Z-xKEqoDbUjRcKFnj08vhYNV_w',
    appId: '1:697443357296:web:325ba221876d7278bb5ab5',
    messagingSenderId: '697443357296',
    projectId: 'hlrc-projeto',
    authDomain: 'hlrc-projeto.firebaseapp.com',
    storageBucket: 'hlrc-projeto.firebasestorage.app',
    measurementId: 'G-3VQRC24C9H',
  );
}
